"""init_db_v7

Revision ID: 89960124f1f5
Revises: 
Create Date: 2026-08-30 20:06:00.336315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '89960124f1f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('img_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', 'LOST', 'EXPIRED', name='status'), nullable=False),
    sa.Column('is_platform', sa.Boolean(), nullable=False),
    sa.Column('ticket_expiration_value', sa.Integer(), nullable=True),
    sa.Column('ticket_expiration_unit', sa.Enum('HOURS', 'DAYS', name='expirationunit'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sa.Enum('PLATFORM', 'COMPANY', name='rolescope'), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', 'LOST', 'EXPIRED', name='status'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('nro_batch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('batch_status', sa.Enum('AVAILABLE', 'ASSIGNED', 'DEFECTIVE', 'LOST', name='batchstatus'), nullable=False),
    sa.Column('physical_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upasser_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chips_nro_batch'), 'chips', ['nro_batch'], unique=False)
    op.create_index(op.f('ix_chips_physical_uuid'), 'chips', ['physical_uuid'], unique=True)
    op.create_index(op.f('ix_chips_upasser_uuid'), 'chips', ['upasser_uuid'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ci', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_ci'), 'clients', ['ci'], unique=True)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_table('roles_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('NFC', 'QR', 'BLE', 'PIN', name='credentialtype'), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', 'LOST', 'EXPIRED', name='status'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('chip_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['chip_id'], ['chips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_public_id'), 'credentials', ['public_id'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('mac_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chip_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fw_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', 'LOST', 'EXPIRED', name='status'), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address')
    )
    op.create_table('roles_users',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'user_id')
    )
    op.create_table('users_permissions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('zones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_credential',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('assignment_status', sa.Enum('PENDING', 'ACTIVE', name='assignmentstatus'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direction', sa.Enum('ENTRY', 'EXIT', name='direction'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('qr_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'USED', 'EXPIRED', 'CANCELLED', name='ticketstatus'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_qr_code'), 'tickets', ['qr_code'], unique=True)
    op.create_table('access',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('result', sa.Enum('GRANTED', 'DENIED', name='accessresult'), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gate_id', sa.UUID(), nullable=False),
    sa.Column('client_credential_id', sa.UUID(), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('client_credential_id IS NOT NULL OR ticket_id IS NOT NULL', name='access_credential_or_ticket_required'),
    sa.ForeignKeyConstraint(['client_credential_id'], ['client_credential.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('wallet_type', sa.Enum('MAIN', 'BONUS', 'COURTESY', name='wallettype'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('client_credential_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('amount >= 0', name='wallet_amount_non_negative'),
    sa.CheckConstraint('client_id IS NOT NULL OR client_credential_id IS NOT NULL', name='wallet_owner_required'),
    sa.ForeignKeyConstraint(['client_credential_id'], ['client_credential.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_credential_id', 'wallet_type', name='uq_wallet_credential_type'),
    sa.UniqueConstraint('client_id', 'wallet_type', name='uq_wallet_client_type')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('access_id', sa.UUID(), nullable=True),
    sa.Column('client_credential_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('amount != 0', name='transaction_amount_nonzero'),
    sa.CheckConstraint('wallet_id IS NOT NULL OR ticket_id IS NOT NULL', name='transaction_wallet_or_ticket_required'),
    sa.ForeignKeyConstraint(['access_id'], ['access.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_credential_id'], ['client_credential.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('wallets')
    op.drop_table('access')
    op.drop_index(op.f('ix_tickets_qr_code'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('gates')
    op.drop_table('client_credential')
    op.drop_table('zones')
    op.drop_table('users_permissions')
    op.drop_table('roles_users')
    op.drop_table('devices')
    op.drop_index(op.f('ix_credentials_public_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles_permissions')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_ci'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_chips_upasser_uuid'), table_name='chips')
    op.drop_index(op.f('ix_chips_physical_uuid'), table_name='chips')
    op.drop_index(op.f('ix_chips_nro_batch'), table_name='chips')
    op.drop_table('chips')
    op.drop_table('branches')
    op.drop_table('types')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('companies')
    # ### end Alembic commands ###
